import type { Peer, AnnounceResponse } from "../../../shared";
import * as dgram from "node:dgram";
import crypto from "node:crypto";

function udpClient(
  socket: dgram.Socket,
  message: Buffer,
  port: number,
  host: string,
  timeoutMs = 5000
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      socket.off("message", onMessage);
      socket.off("error", onError);
      reject(
        new Error(`UDP Tracker request to ${host}:${port} timed out`)
      );
    }, timeoutMs);

    const onMessage = (msg: Buffer) => {
      clearTimeout(timer);
      socket.off("message", onMessage);
      socket.off("error", onError);
      resolve(msg);
    };

    // An unhandled "error" event on a dgram socket throws and
    // crashes the process (e.g. ICMP port unreachable), so it
    // must always have a listener attached.
    const onError = (err: Error) => {
      clearTimeout(timer);
      socket.off("message", onMessage);
      socket.off("error", onError);
      reject(err);
    };

    socket.once("message", onMessage);
    socket.once("error", onError);

    socket.send(message, port, host, (err) => {
      if (err) {
        clearTimeout(timer);
        socket.off("message", onMessage);
        socket.off("error", onError);
        reject(err);
      }
    });
  });
}

export async function udpTrackerClient(
  infoHash: string,
  peerId: string,
  trackerUrl: string
): Promise<AnnounceResponse> {
  const socket = dgram.createSocket("udp4");

  try {
    const url = new URL(trackerUrl);

    const host = url.hostname;

    if (!url.port) {
      throw new Error("UDP tracker URL must contain a port");
    }

    const port = Number(url.port);

    if (!Number.isInteger(port) || port < 1 || port > 65535) {
      throw new Error(`Invalid UDP tracker port: ${url.port}`);
    }

    // ================================================================
    // CONNECT PHASE
    //
    // Request:
    //
    // Offset  Size
    // 0       8     Protocol ID
    // 8       4     Action
    // 12      4     Transaction ID
    //
    // Response:
    //
    // Offset  Size
    // 0       4     Action
    // 4       4     Transaction ID
    // 8       8     Connection ID


    const PROTOCOL_ID = 0x41727101980n;

    // This is generated by us.
    // It is NOT the connection ID.
    const connectTxId = crypto.randomInt(0, 0x7fffffff);

    const connectReq = Buffer.alloc(16);

    connectReq.writeBigInt64BE(PROTOCOL_ID, 0);
    connectReq.writeInt32BE(0, 8); // Action = Connect
    connectReq.writeInt32BE(connectTxId, 12);

    const connectResponse = await udpClient(
      socket,
      connectReq,
      port,
      host
    );

    // An error response (Action 3) is only guaranteed to be 8
    // bytes long, so handle it before demanding a full response.
    if (connectResponse.length < 8) {
      throw new Error("Invalid connect response");
    }

    const connectAction = connectResponse.readInt32BE(0);
    const returnedConnectTxId = connectResponse.readInt32BE(4);

    // Action 3 = Error
    if (connectAction === 3) {
      const message = connectResponse
        .subarray(8)
        .toString();

      throw new Error(`UDP tracker error: ${message}`);
    }

    if (connectAction !== 0) {
      throw new Error(
        `Unexpected connect action: ${connectAction}`
      );
    }

    if (returnedConnectTxId !== connectTxId) {
      throw new Error("Connect transaction ID mismatch");
    }

    if (connectResponse.length < 16) {
      throw new Error("Invalid connect response");
    }

    // This is the actual connection ID returned by the tracker.
    const connectionId = connectResponse.readBigInt64BE(8);

    // ================================================================
    // ANNOUNCE PHASE
    //
    // Offset  Size
    // 0       8     Connection ID
    // 8       4     Action
    // 12      4     Transaction ID
    // 16      20    Info Hash
    // 36      20    Peer ID
    // 56      8     Downloaded
    // 64      8     Left
    // 72      8     Uploaded
    // 80      4     Event
    // 84      4     IP
    // 88      4     Key
    // 92      4     Num Want
    // 96      2     Port

    const announceTxId = crypto.randomInt(0, 0x7fffffff);
    const announceReq = Buffer.alloc(98);

    announceReq.writeBigInt64BE(connectionId, 0);
    announceReq.writeInt32BE(1, 8); // Action = Announce
    announceReq.writeInt32BE(announceTxId, 12);

    // ------------------------------------------------
    // Info Hash
    // ------------------------------------------------

    if (!/^[0-9a-fA-F]{40}$/.test(infoHash)) {
      throw new Error(
        "Invalid info hash: expected 40 hexadecimal characters"
      );
    }

    const infoHashBuffer = Buffer.from(infoHash, "hex");

    infoHashBuffer.copy(announceReq, 16);

    // Peer ID
    // Assuming peerId is a normal 20-byte string,
    // e.g. "-MT0001-abcdefghijkl"
    //

    const peerIdBuffer = Buffer.from(peerId);

    if (peerIdBuffer.length !== 20) {
      throw new Error(
        `Invalid peer ID: expected 20 bytes, got ${peerIdBuffer.length}`
      );
    }

    peerIdBuffer.copy(announceReq, 36);
    announceReq.writeBigInt64BE(0n, 56);
    announceReq.writeBigInt64BE(0n, 64);
    announceReq.writeBigInt64BE(0n, 72);
    announceReq.writeInt32BE(2, 80);
    announceReq.writeUInt32BE(0, 84);
    announceReq.writeUInt32BE(
      crypto.randomInt(0, 0xffffffff),
      88
    );
    announceReq.writeInt32BE(-1, 92);


    announceReq.writeUInt16BE(6881, 96);

    const announceResponse = await udpClient(
      socket,
      announceReq,
      port,
      host
    );

    // An error response (Action 3) is only guaranteed to be 8
    // bytes long, so handle it before demanding a full response.
    if (announceResponse.length < 8) {
      throw new Error("Invalid announce response");
    }

    const announceAction = announceResponse.readInt32BE(0);

    const returnedAnnounceTxId =
      announceResponse.readInt32BE(4);

    // Action 3 = Error
    if (announceAction === 3) {
      const message = announceResponse
        .subarray(8)
        .toString();

      throw new Error(`UDP tracker error: ${message}`);
    }

    if (announceAction !== 1) {
      throw new Error(
        `Unexpected announce action: ${announceAction}`
      );
    }

    if (returnedAnnounceTxId !== announceTxId) {
      throw new Error(
        "Announce transaction ID mismatch"
      );
    }

    if (announceResponse.length < 20) {
      throw new Error("Invalid announce response");
    }

    // ================================================================
    // ANNOUNCE RESPONSE
    //
    // Offset  Size
    // 0       4     Action
    // 4       4     Transaction ID
    // 8       4     Interval
    // 12      4     Leechers
    // 16      4     Seeders
    // 20      ...   Peers
    // ================================================================

    const interval = announceResponse.readUInt32BE(8);
    const leechers = announceResponse.readUInt32BE(12);
    const seeders = announceResponse.readUInt32BE(16);

    const peers: Peer[] = [];

    // Compact IPv4 peer list.
    // Each peer = 4 bytes IP + 2 bytes port = 6 bytes.
    const peerDataLength = announceResponse.length - 20;
    const usablePeerLength = peerDataLength - (peerDataLength % 6);

    for (
      let i = 20;
      i < 20 + usablePeerLength;
      i += 6
    ) {
      const ip = `${announceResponse[i]}.${announceResponse[i + 1]}.${announceResponse[i + 2]}.${announceResponse[i + 3]}`;

      const peerPort = announceResponse.readUInt16BE(i + 4);

      peers.push({
        ip,
        port: peerPort,
      });
    }

    return {
      interval,
      complete: seeders,
      incomplete: leechers,
      peers,
    };
  } finally {
    socket.close();
  }
}
